### ISSUE TITLE
jquery-nearest and sliders

### ISSUE THREAD

**Issue by sashberd** [gilmoreorless/jquery-nearest#30]
Hey guys,

First of all, Great Work!!! Thanks for such perfect jquery plugin.

My question is about sliders and your plugin work.
For example, on this page http://auto.qq.com/ (sorry for Chinese) there is a main slider with images.
If I take one of sliders images and onmousemove on it trying to get nearest with you plugin I get 4 another images of this slider, even though the distance on X and Y is 0. 
Is there is a way to avoid return elements that starts with the same X and Y points and has same width and height like in this specific slider example.
Thanks for help guys.

**Comment by gilmoreorless** [comment]
Hi @sashberd.

I've had a look at your page, but I can't quite get what you're trying to do. You said you're trying to get the nearest, but the nearest of what type of element?
Perhaps the `selector` option of the plugin could handle your use case. For example, add a special CSS class (or `data-` attribute) to the elements you're trying to find, but don't add it to the elements you want to exclude. Then use that special class or attribute in the call to `.nearest()`

Cheers,
Gil

**Comment by sashberd** [comment]
Here is the code I'm using:

``` javascript
$(document).on('mousemove', function(e) {        
                    var $element = $.nearest({
                        x: e.pageX,
                        y: e.pageY
                        //sameY: true                        
                    }, 'img'));
                    if ($element && $element.length) {
                       ....
                    }
                }
            });
```

Here the scenario i'm trying to solve. I`m hover mouse on main image slider (http://auto.qq.com/). The code above will give me 4 images that are indeed nearest to hovered image cause the divergence on X and Y equals 0. Is there is a way to pass such elements (in my case images) that have X and Y divergence 0?

Thanks

**Comment by gilmoreorless** [comment]
Ah, I see. There is no current way to automatically exclude multiple elements with identical dimensions. In fact, I'm not sure I'd want to add that feature, as it seems to go against one of the main use cases of this plugin.

This seems like the kind of scenario that is best handled by some extra filtering in your own code after calling `.nearest()`

**Comment by sashberd** [comment]
Thanks man,

For this specific case I added this code to your plugin and now it is works fine for me.

``` javascript
 cache = cache.filter(function(item) {
            return item.dist;
        });
```

Thanks for cooperation
Alex
